apiVersion: v1
kind: Pod
metadata:
  name: jenkub
  labels:
    name: jenkub
spec:
  containers:
    - resources:
        limits :
          cpu: 4
          memory: 8192Mi
      image: singen/jenkub
      name: jenkub

      ports:
        - containerPort: 8080
          name: webjenkins
