apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
  labels:
    name: jenkins
    role: leader
spec:
  replicas: 1
  selector:
    name: jenkins
    role: leader
  template:
    metadata:
      name: jenkins
      labels:
        name: jenkins
        role: leader
    spec:
      containers:
      - name: jenkins
        image: singen/jenkub
        ports:
        - name: ui
          containerPort: 8080
        - name: jdescovery
          containerPort: 50000
