apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
  labels:
    name: jenkins
    role: leader
spec:
  replicas: 1
  selector:
    name: jenkins
    role: leader
  template:
    metadata:
      name: jenkins
      labels:
        name: jenkins
        role: leader
    spec:
      volumes:
      - name: nasjenkins
        nfs:
          # Use real NFS server address here.
          server: nas
          # Use real NFS server export directory.
          path: "/big-kube1/kube/pv/jenkins"
          readOnly: false
      - name: nas2backup
        nfs:
          server: nas2
          path: "/big-kube2/kube/backup/jenkins"
          readOnly: false
      containers:
      - name: jenkins
        image: singen/jenkub
        imagePullPolicy: Always
        ports:
        - name: ui
          containerPort: 8080
        - name: descover
          containerPort: 50000
        volumeMounts:
          # 'name' must match the volume name below.
          - name: nasjenkins
            # Where to mount the volume.
            mountPath: "/var/jenkins_home"
          - name: nas2backup
            mountPath: "/var/log"
