apiVersion: v1
kind: Service
metadata:
  labels:
    name: jenkins
  name: jenkins
spec:
  type: NodePort
  ports:
  - name: ui
    port: 8080
    targetPort: ui
    protocol: TCP
  - name: discover
    port: 50000
    targetPort: discover
    protocol: TCP
  externalIPs:
    - 198.18.26.31
  selector:
    name: jenkins
    # role: leader
